Removed referral to hardcoded lcov

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -10,10 +10,19 @@ coverage:
   stage: coverage
   tags:
     - code_coverage
+  before_script:
+    - |
+      if ! command -v lcov &> /dev/null; then
+        echo "lcov not found, installing..."
+        apt-get update
+        apt-get install -y lcov
+      else
+        echo "lcov is already installed"
+      fi    
   script:
     - mkdir build
     - cd build
-    - /mathworks/devel/sandbox/dozyurt/3PForR2024b/3p/install/unknown/glnxa64/cmake-bin/glnxa64/bin/cmake -DCMAKE_BUILD_TYPE=DEBUG -DALL_TESTS=ON -DBUILD_SHARED_LIBS=OFF -DHIGHS_COVERAGE=ON -DLCOV_PATH=/home/dozyurt/Downloads/bin/lcov -DGENHTML_PATH=/home/dozyurt/Downloads/bin/genhtml -DCI=OFF -DFAST_BUILD=OFF ..
+    - /mathworks/devel/sandbox/dozyurt/3PForR2024b/3p/install/unknown/glnxa64/cmake-bin/glnxa64/bin/cmake -DCMAKE_BUILD_TYPE=DEBUG -DALL_TESTS=ON -DBUILD_SHARED_LIBS=OFF -DHIGHS_COVERAGE=ON -DCI=OFF -DFAST_BUILD=OFF ..
     - make
     - /mathworks/devel/sandbox/dozyurt/3PForR2024b/3p/install/unknown/glnxa64/cmake-bin/glnxa64/bin/cmake --build . --target coverage
   artifacts:
